object Versions {
    const val coreKtx = "1.9.0"
    const val appCompat = "1.6.1"
    const val material = "1.9.0"
    const val constraintLayout = "2.1.4"
    const val junit = "4.13.2"
    const val extJunit = "1.1.5"
    const val esspresso = "3.5.1"
    const val daggerHilt = "2.43.2"
    const val hiltCompiler = "1.1.0"
    const val navigationKtx = "2.5.3"
    const val hdodenhof = "3.1.0"
    const val glide = "4.16.0"
    const val youtubePlayer = "12.1.0"
    const val sonicCountDown = "1.0.4"
    const val retrofit = "2.9.0"
    const val interceptor = "5.0.0-alpha.6"
    const val lifecycle = "2.6.2"
}